"""Read-only views over the BookIR for the various deliverable files.

The renderer used to dump the entire ``full_markdown`` blob into
``translation-input.md``. That meant apparatus / TOC / index chapters
were sent to the translator even when the BookIR had marked them as
``preserve_original`` and ``resource_only``.

The new :func:`render_translation_input_markdown` filters out:

* chapters whose ``kind`` is in
  :data:`chapter_kind.NON_TRANSLATABLE_CHAPTER_KINDS`
* chapters whose ``translate`` flag is explicitly ``False``
* chapter blocks whose ``kind`` is in
  :data:`chapter_kind.NON_TRANSLATABLE_BLOCK_KINDS` (tables / figures)

The output preserves the heading anchors so chunk-level translation
keys remain stable.
"""

from __future__ import annotations

import re

from .chapter_kind import (
    NON_TRANSLATABLE_BLOCK_KINDS,
    classify_chapter,
    classify_blocks,
    should_translate_block,
    should_translate_chapter,
)


def render_book_markdown(book: dict, *, include_trace: bool = False) -> str:
    key = "trace_markdown" if include_trace else "full_markdown"
    return str(book.get(key) or "")


# --- translation input -----------------------------------------------------

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")
_ASSET_KEEP_RE = re.compile(r"!\[(?P<label>[^\]]*)\]\((?P<path>[^)]+)\)")


def _heading_line(level: int, title: str, chapter_index: int | None) -> str:
    safe_title = (title or "").strip() or (f"Chapter {chapter_index}" if chapter_index else "")
    return f"{'#' * level} {safe_title}".rstrip()


def _filter_block_text(text: str) -> str:
    """Drop standalone image-asset markdown lines (tables/figures).

    We keep the link syntax as a no-op reference so translators still see
    that something was there, but we strip the inline image markdown that
    would otherwise be sent verbatim.
    """
    if not text:
        return text
    lines: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("!["):
            # keep the file path as a plain reference without image syntax
            match = _ASSET_KEEP_RE.match(stripped)
            if match:
                lines.append(f"[Figure/Table: {match.group('label') or 'asset'}]")
                continue
            lines.append("[Figure/Table]")
            continue
        lines.append(line)
    return "\n".join(lines)


def render_translation_input_markdown(book: dict) -> str:
    """Build ``translation-input.md`` honouring chapter/block kinds.

    The function never mutates ``book``; if a chapter lacks a ``kind``
    field, it is classified on the fly via
    :func:`chapter_kind.classify_chapter` so existing BookIRs without
    the new field still get the right default.
    """
    if not isinstance(book, dict):
        return ""
    chapters = book.get("chapters") or []
    pages = book.get("pages") or []
    if not chapters:
        # nothing structured; fall back to legacy full_markdown
        return str(book.get("full_markdown") or "")

    out: list[str] = []
    out.append("<!-- translation input: generated by book_views.render_translation_input_markdown -->\n")
    for chapter in chapters:
        if not isinstance(chapter, dict):
            continue
        # ensure a kind is filled in (in-memory only)
        chapter.setdefault("kind", classify_chapter(chapter, pages=pages))
        if not should_translate_chapter(chapter):
            out.append(
                f"\n<!-- chapter skipped: {chapter.get('chapter_id', '')} "
                f"kind={chapter['kind']} title={chapter.get('title', '')!r} -->\n"
            )
            continue
        title = str(chapter.get("title") or "").strip()
        if title:
            out.append(_heading_line(2, title, chapter.get("index")))
        markdown = str(chapter.get("markdown") or "")
        # filter block-level non-translatable items if the chapter has
        # structured blocks; otherwise fall back to a heuristic line
        # filter on the markdown text.
        blocks = chapter.get("blocks")
        if isinstance(blocks, list) and blocks:
            classify_blocks(blocks)
            kept = [blk.get("markdown") or blk.get("text") or "" for blk in blocks if should_translate_block(blk)]
            markdown = "\n\n".join(piece for piece in kept if piece)
        else:
            markdown = _filter_block_text(markdown)
        if markdown.strip():
            out.append("")
            out.append(markdown.rstrip())
            out.append("")
    return "\n".join(out).rstrip() + "\n"


# kept for backward-compatibility with other call sites
__all__ = [
    "render_book_markdown",
    "render_translation_input_markdown",
]
